# -*- coding: utf-8 -*-
"""correct_date.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/168VF123qwRpjZWIlW6AYrt1wn4ZO4NlY
"""

import pandas as pd
from datetime import datetime

#Prepare
#data = pd.read_csv('SAFETY_GPS.csv')\n",

def correct_date(data):

  data = data[pd.notna(data['DESCRIPTION'])]

  def hasNumbers(inputString):
    return any(char.isdigit() for char in inputString)

  correction_index = []
  corrections_counter = 0
  
  for index, case in zip(data.index, data['INCIDENT DATE']):
    if not hasNumbers(case):
      print('dropping non-numeric INCIDENT DATE at index {}'.format(index))
      data.drop(data.index[index], inplace=True)
      corrections_counter += 1
    if len(case) != 19 and hasNumbers(case):
      objDate = datetime.strptime(case, '%d/%m/%y %H:%M')
      string_date = datetime.strftime(objDate,'%Y-%m-%d %H:%M:%S')
      print('correction done at index {}: {} --> {}'.format(index, case, string_date))
      data.at[index, 'INCIDENT DATE'] = string_date
      corrections_counter += 1
      
  print('nothing to correct...') if corrections_counter == 0 else print('number of corrections = ', corrections_counter)
  return data

#Execute
#corrected_data = correct_date(data)